---
title: "Task 12"
author: "Logan Morrill"
date: "10/5/2021"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---

```{r include = FALSE}
#Packages
library(tidyverse)
library(downloader)
library(readxl)
```

```{r include = FALSE}
#Load Data
movie_data <- tempfile()
download("https://raw.githubusercontent.com/fivethirtyeight/data/master/fandango/fandango_score_comparison.csv", movie_data, mode = "wb")
movie_ratings <- read_csv(movie_data)

str(movie_ratings)
```

```{r include = FALSE}
#Filter for similar movie ratings
ratings <- movie_ratings %>%
  select(FILM, Fandango_Ratingvalue, RT_norm, Metacritic_norm, IMDB_norm) %>%
  pivot_longer(2:5, names_to = "rater", values_to = "rating") %>%
  select(FILM, rater, rating) %>%
  head(n = 20)
ratings
```

```{r Moving Ratings}
ggplot(ratings, aes(x = FILM, y = rating, color = rater)) +
  geom_point() +
  geom_line(aes(group = rater)) +
  scale_y_discrete( 
                    limits = c("1","2","3","4","5"), breaks = c("1","2","3","4","5")) +
  scale_color_discrete(name = "Critic", labels = c("Fandango", "IMDB", "Metacritic","Rotten Tomatoes")) +
  labs(x = 'Film', y = 'Rating', title = 'Moving Ratings') +
  theme_bw()
```
For the graph, I plotted the rating with a point and made a line to show the different trends among different critics. Fandango seems to give higher ratings. Fandango ratings also do not seem to change much. For half of the films, the ratings seem to be similar. However, for the other half the ratings are all over the place.
