---
title: "Task 4"
author: "Logan Morrill"
date: "9/7/2021"
output: 
  html_document:
    theme: united
    keep_md: True
---
#### Load Packages
```{r Packages}
library(dplyr)
```
#### Load iris data
```{r Load iris data}

iris_data <- tibble(iris)
str(iris_data)
tail(iris_data)
```
#### Arrange iris data based on Sepal.Length
```{r Arrange iris data}
head(arrange(iris_data, Sepal.Length), n = 10)
```
#### Select Species and Petal.Width
```{r Select operator}
testdat <- select(iris_data, Species, Petal.Width)
head(testdat)
```
#### Find species means
```{r Species Means}
species_mean <- 
  iris_data %>%
  group_by(Species) %>%
  summarise(
    Sepal_Width_Mean = mean(Sepal.Width), Sepal_Length_Mean = mean(Sepal.Length),Petal_Width_Mean = 
    mean(Petal.Width), Petal_Length_Mean = mean(Petal.Length))

species_mean

```
#### Filter Iris data based on Sepal.Width & Petal.Width
```{r Iris min}
iris_min <- filter(iris_data, Sepal.Width <= 3, Petal.Width != 2.5)
head(iris_min)
```
#### Categorize Sepal.Length
```{r Iris size}
iris_size <- iris_data %>%
  mutate(Sepal.Size =
          case_when(
            Sepal.Length < 5 ~ "small", 
            Sepal.Length >= 5 & Sepal.Length < 6.5 ~ "medium",
            Sepal.Length >= 6.5 ~ "large"))
iris_size
```
#### Rank Petal.Length
```{r Iris rank}
iris_rank <- arrange(iris_data, desc(Petal.Length))
iris_rank
```
#### Stdevs and means for each Species
```{r Stdev and Means}
?summarize_all()
mean_by_species <-
  iris_data %>%
  group_by(Species) %>%
  summarize_all(list(Mean = mean,Std_dev = sd))

mean_by_species
```

### Report
##### Question 1
```{r Question 1}
#Is there a relationship between livestock prices and crop prices?

#When 5 people were asked for feedback they seemed generally uninterested in the topic.
#When a farmer was asked for feedback, he said there seems to be a relationship because they are both raised on a similar type of land and are in a similar market.
#After quick research it seems there is a inverse relationship between livestock prices and crop prices.
```

##### Question 2
```{r Question 2}
#Why is it recommended to get 8 hours of sleep?

#When 5 people were asked for feedback they seemed interested in the topic but believed the answer would not influence their sleep schedule.
#When a sleep doctor was asked for feedback, he said it is important to get around 7-9 hours of sleep because it has several benefits to your health.
#After quick research it seems the doctor was right about the benefits of getting enough sleep.
```

##### Question 3
```{r Question 3}
#How has modern science played a role in life expectancy?

#When 5 people were asked for feedback they seemed interested in the topic and were interested in the results.
#When a pharmacist was asked for feedback, she said it was a complicated answer because several aspects have contributed to an increase in modern life expectancy.
#After quick research it seems there are several aspects that have played a role in life expectancy increasing and it seems it will take longer than 2 months to complete.
```