---
title: "Interactive Maps"
author: "Logan Morrill"
date: "11/16/2021"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---

```{r include = FALSE}
#Packages
pacman::p_load(tidyverse,maps,USAboundaries,leaflet)
```

```{r include = FALSE}
#Load Data
states <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
id <- us_counties(states = "ID")

cities <- us_cities()
```

```{r Get Cities}
#Largest 3 cities in each state
top_3 <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii') %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)
#Largest city in each state
top <- top_3 %>%
  slice(1:1)
#2nd largest cities in each state
top_2nd <- top_3 %>%
  slice(2:2)
#3rd largest cities in each state
top_3rd <- top_3 %>%
  slice(3:3)
#Get longitude and latitude
top_city <- top %>%
  mutate(coords = geometry) %>%
  separate(coords, into = c("long", "lat"), sep = ',') %>%
  separate(long, into = c("no", "Long"), sep = 2) %>%
  separate(lat, into = c("Lat", "No"), sep = -1) %>%
  mutate(Lat = as.numeric(Lat), Long = as.numeric(Long))

```

```{r City Map}
#Graph
leaflet() %>% 
  addTiles() %>%
  addPolygons(data = states, fillColor = 'white', weight = 1, opacity = 1, color = 'grey', fillOpacity = 0.7) %>%
  addPolygons(data = id, fillColor = 'white', weight = 1, opacity = 1, color = 'grey', fillOpacity = 0.7) %>%
  addCircleMarkers(data = top, radius = 4, color = 'navy', stroke = FALSE, fillOpacity = 0.5) %>%
  addCircleMarkers(data = top_2nd, radius = 4, color = 'royalblue', stroke = FALSE, fillOpacity = 0.5) %>%
  addCircleMarkers(data = top_3rd, radius = 4, color = 'skyblue', stroke = FALSE, fillOpacity = 0.5) %>%
  addMarkers(data = top_city, lat = ~Lat, lng = ~Long, popup = ~as.character(population), label = ~city)

```
