---
title: "Task 8"
author: "Logan Morrill"
date: "9/21/2021"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---

```{r include = False}
#Packages
library(tidyverse)
library(downloader)
library(readxl)
```
### Load Data
```{r Load Data}
HeightData <- tempfile()
download("https://raw.githubusercontent.com/hadley/r4ds/master/data/heights.csv", HeightData, mode = "wb")
Height <- read_csv(HeightData)
head(Height)
```
### Add new column to specify grade
```{r}
HeightEd <- Height %>%
  mutate(grade =
          case_when(
            ed >= 3 & ed <= 6 ~ "primary", 
            ed >= 7 & ed <= 11 ~ "secondary",
            ed == 12 ~ "highschoolgrad",
            ed >= 13 & ed <= 15 ~ "associate",
            ed == 16 ~ "bachelors",
            ed == 17 | ed == 18 ~ "mastersdoctorate"))
```
### Relationship between education and race
```{r Education and Race}
HeightEd %>%
  mutate(grade = as.factor(fct_reorder(grade, earn))) %>%
  ggplot(aes(x = grade, y = earn, fill = race)) +
    geom_boxplot()
```
### Relationship between education and sex
```{r Education and Sex}
HeightEd %>%
  mutate(grade = as.factor(fct_reorder(grade, earn))) %>%
  ggplot(aes(x = grade, y = earn, fill = sex)) +
    geom_boxplot()
```

```{r}
HeightEd %>%
  mutate(grade = fct_relevel(grade, 
            "primary", "secondary", "highschoolgrad", 
            "associate", "bachelors", "mastersdoctorate"), 
         grade = fct_collapse(grade,
                                "3-6" = "primary",
                                "7-11" = "secondary",
                                "12" = "highschoolgrad",
                                "13-15" = "associate",
                                "16" = "bachelors",
                                "17-18" = "mastersdoctorate")) %>%
  ggplot(aes(x = grade, y = age, fill = grade)) +
    geom_boxplot() +
    labs(x = "Grades", y = "Age", title = "Age ranges for various grades") +
    theme_bw() +
    theme(legend.position = "none")
```

