---
title: "Same Data, Different Format, and Tidy"
author: "Logan Morrill"
date: "10/7/2021"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---

```{r include = FALSE}
#Packages
library(tidyverse)
library(haven)
library(readxl)
library(downloader)
```

```{r include = FALSE}
#Load Data

#Rds Data
rds_data <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS?raw=true", rds_data , mode = "wb")
dart_expert_rds <- read_rds(rds_data)

#Csv Data
csv_data <- tempfile()
download("https://raw.githubusercontent.com/WJC-Data-Science/DTS350/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.csv", csv_data , mode = "wb")
dart_expert_csv <- read_csv(csv_data)

#Dta Data
dta_data <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.dta?raw=true", dta_data , mode = "wb")
dart_expert_dta <- read_dta(dta_data)

#Sav Data
sav_data <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.sav?raw=true", sav_data, mode = "wb")
dart_expert_sav <- read_sav(sav_data)

#xlsx Data
xlsx_data <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.xlsx?raw=true", xlsx_data, mode = "wb")
dart_expert_xlsx <- read_xlsx(xlsx_data)

```

```{r include=FALSE}
#Confirm data is equal
all_equal(dart_expert_rds, dart_expert_csv, dart_expert_dta, convert = TRUE)
all_equal(dart_expert_csv, dart_expert_sav, dart_expert_xlsx, convert = TRUE)
```

```{r BoxPlot}
ggplot(dart_expert_csv, aes(x = variable, y = value, fill = variable)) +
  geom_boxplot()
```

```{r Jittered Returns}
ggplot(dart_expert_csv, aes(x = variable, y = value)) +
  geom_jitter(aes(color = variable))
```

```{r Average Returns}
ggplot(dart_expert_csv, aes(x = contest_period, y = value, group = variable)) +
  geom_line(aes(color = variable))
```

```{r}
DJIA_returns <- dart_expert_csv %>%
  filter(variable == 'DJIA') %>%
  mutate(contest_period = str_replace_all(contest_period, '19', '_19'),
         contest_period = str_replace(contest_period, 'Febuary', 'February'),
         contest_period = str_replace(contest_period, 'Dec._1993', 'December_1993')) %>%
  separate(contest_period, into = c("Month", "year_end"), sep = '-') %>%
  separate(year_end, into = c("Month", "year"), sep = '_') %>%
  pivot_wider(names_from = "year", values_from = "value") %>%
  arrange(factor(Month, levels = month.name)) %>%
  select(-variable)
view(DJIA_returns)
```

```{r include = FALSE}
#Create RDS file
saveRDS(DJIA_returns, file = "DJIA_returns.rds")
```

```{r DJIA plot}
DJIA_returns %>%
  pivot_longer(2:10, names_to = "year", values_to = "return", values_drop_na = TRUE) %>%
  ggplot(aes(x = year, y = return, group = Month)) +
    geom_point(aes(color = Month)) +
    geom_line(aes(color = Month)) +
    facet_wrap(~Month, scales = 'free_x') +
    labs(x = 'Year', y = 'Return' , title = 'Dow Jones returns 1990:1998') +
    theme_bw() +
    theme(legend.position = 'none', axis.text.x = element_text(angle = 45))
```
The Boxplot shows that PROS has the highest return. However, the jitter plot shows the DJIA has the least variable returns and DARTS and PROS have similar variability. The geom_point confirms the jitter plot. The last plot shows the average return of the Dow from 1990 to 1998 and is grouped by month.


