---
title: "Task 4"
author: "Logan Morrill"
date: "9/7/2021"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---

##### Load Packages
```{r Packages}
library(tidyverse)
library(dplyr)
library(downloader)
library(readxl)
```
##### Load Data
```{r Load Data}
SoloData <- tibble(read.csv("solo-artist-followers.csv"))
head(SoloData)
BillboardData <- tibble(read.csv("billboard-hits.csv"))
str(BillboardData)

#Change peak_date to date
BillboardData <- read_csv(
  ("billboard-hits.csv"),
  col_types = cols(
    peak_date = col_date()
  )
)
str(BillboardData)
```

All data types seem to be imported correctly, except the peak_date for billboard data.
Peak_date had to be converted to data type date.


```{r Filter billboard data}
atleast_six_hits <- BillboardData %>%
  group_by(name) %>%
  filter(n() > 6 & band != "")

view(atleast_six_hits)
str(atleast_six_hits)
```

```{r Get Band Hits}
band_hits <- BillboardData %>% 
  group_by(band) %>%
  filter(name %in% atleast_six_hits$band)
#Switch band and name column data
band_hits <- rename(band_hits, band = name, name = band)
view(band_hits)
```

```{r Graphing}
ggplot(data = atleast_six_hits, aes(x = peak_date, y = peak_rank, color = name, group = name)) +
  geom_point() +
  geom_line() +
  geom_point(data = band_hits, color = 'black') +
  geom_line(data = band_hits, color = 'black',linetype = 'dotted') +
  facet_wrap(~band, scales = "free") +
  theme_bw()
```

c